---

- name: setup:path:bashrc
  lineinfile:
    dest: "{{ item }}"
    state: "present"
    regexp: "{{ '^export PATH=' + tools.path.bin | regex_escape() + ':\\$PATH' }}"
    line: "export PATH={{ tools.path.bin }}:$PATH"
    backup: "yes"
  ignore_errors: True # ignore if file is missing
  with_items: "{{ tools.rc }}"
