---

- name: "tools:create-wrappers | Make sure all wrappers present"
  template:
    src: templates/wrapper.j2
    dest: "{{ tools.path.bin }}/{{ item.name }}"
    mode: "{{ item.mode|default(tools.default.mode) }}"
    force: "{{ item.force|default(1, true) }}"
  with_items: "{{ tools.executables }}"
  when: item.type == "wrapper"

- name: "tools:create-binstubs | Make sure all binstubs present"
  template:
    src: templates/binstub.j2
    dest: "{{ tools.path.bin }}/{{ item.name }}"
    mode: "{{ item.mode|default(tools.default.mode) }}"
    force: "{{ item.force|default(1, true) }}"
  with_items: "{{ tools.executables }}"
  when: item.type == "autoconfig"

- name: "tools:create-links | Make sure all links present"
  file:
    src: "{{ tools.path.share }}/{{ item.target }}"
    dest: "{{ tools.path.bin }}/{{ item.name }}"
    mode: "{{ item.mode|default(tools.default.mode) }}"
    force: "{{ item.force|default(1, true) }}"
    state: "link"
  with_items: "{{ tools.executables }}"
  when: item.type == "link"
